# Generated by Django 6.0 on 2026-01-15 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('group_home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guardian_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('GUARDIAN', 'Guardian'), ('AGENT', 'Agent')], max_length=20, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('DOCS_PENDING', 'Docs Pending'), ('ONBOARDING_IN_PROGRESS', 'Onboarding In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=30, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.address')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_leads', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadGroupHomeAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('room_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACTIVE', 'Active'), ('MOVED_OUT', 'Moved Out')], default='ACTIVE', max_length=20)),
                ('admission_type', models.CharField(blank=True, choices=[('ASSISTED_LIVING', 'Assisted Living'), ('RESPITE', 'Respite'), ('HOSPICE', 'Hospice')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('financial_effective_date', models.DateField(blank=True, null=True)),
                ('resubmitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group_homes', to=settings.AUTH_USER_MODEL)),
                ('group_home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments', to='group_home.grouphome')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_home_assignments', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_group_home_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead'], name='lead_group__lead_id_5fc86d_idx'), models.Index(fields=['group_home'], name='lead_group__group_h_3f2442_idx'), models.Index(fields=['status'], name='lead_group__status_5ee68e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('lead',), name='unique_active_assignment_per_lead')],
            },
        ),
    ]
