# Generated by Django 6.0 on 2026-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgrouphomeassignment',
            name='occupancy_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('SECOND_RESIDENT', '2nd Resident')], max_length=20, null=True),
        ),
    ]
