# Generated by Django 6.0 on 2026-01-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadgrouphomeassignment_occupancy_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='type',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
