# Generated by Django 6.0 on 2026-01-21 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_home', '0001_initial'),
        ('leads', '0003_remove_lead_type_lead_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadgrouphomeassignment',
            name='room_id',
        ),
        migrations.AddField(
            model_name='leadgrouphomeassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='group_home.grouphomeroom'),
        ),
    ]
