# Generated by Django 6.0 on 2026-02-12 13:55

from django.conf import settings
from django.db import migrations, models


def resolve_duplicate_active_assignments_per_room(apps, schema_editor):
    """Keep one ACTIVE assignment per room; set duplicate ACTIVE rows to MOVED_OUT."""
    LeadGroupHomeAssignment = apps.get_model("leads", "LeadGroupHomeAssignment")
    from django.db.models import Count

    # Rooms with more than one ACTIVE assignment
    dupes = (
        LeadGroupHomeAssignment.objects.filter(status="ACTIVE", room__isnull=False)
        .values("room")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    room_ids = [d["room"] for d in dupes]

    for room_id in room_ids:
        # Order by id descending so we keep the "newest" one
        assignments = list(
            LeadGroupHomeAssignment.objects.filter(room_id=room_id, status="ACTIVE")
            .order_by("-id")
        )
        # Keep first (newest), deactivate the rest
        for a in assignments[1:]:
            a.status = "MOVED_OUT"
            a.save(update_fields=["status"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('group_home', '0002_alter_grouphome_emergency_contact_number'),
        ('leads', '0004_remove_leadgrouphomeassignment_room_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate_active_assignments_per_room, noop),
        migrations.AddConstraint(
            model_name='leadgrouphomeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('room',), name='unique_active_assignment_per_room'),
        ),
    ]
