# Generated by Django 6.0 on 2026-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='group_home_name',
            field=models.CharField(blank=True, help_text='Group home name at the time this log was created', max_length=255, null=True),
        ),
    ]
