# Generated by Django 6.0 on 2026-02-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_auditlog_group_home_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='group_home_name',
            new_name='log_group_home_name',
        ),
    ]
