# Generated by Django 6.0 on 2026-02-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_rename_group_home_name_auditlog_log_group_home_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user_name',
            field=models.CharField(blank=True, help_text='Target user name at the time this log was created', max_length=255, null=True),
        ),
    ]
