# Generated by Django 6.0 on 2026-01-28 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_remove_leadgrouphomeassignment_room_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(unique=True)),
                ('form_name', models.CharField(max_length=255)),
                ('form_code', models.CharField(choices=[('MEDICAL_DEFERMENT_FORM', 'Medical Deferment Form'), ('HEALTH_HISTORY_FORM', 'Health History Form'), ('5_AND_30_DAY_NURSING_TRANSITION_EVALUATION_FORM', '5 And 30 Day Nursing Transition Evaluation Form'), ('RESIDENT_INVENTORY_LIST', 'Resident Inventory List'), ('FIRE_SAFETY_ASSESSMENT', 'Fire Safety Assessment'), ('HRST_MONTHLY_TRACKER', 'HRST Monthly Tracker'), ('CAFC_BSP_TEMPLATE', 'CAFC BSP (Behaviour Support Plan) Template'), ('MED_DISPOSAL_SHEET', 'Medication Disposal Sheet'), ('HRC_BSP_APPROVAL_REQUEST', 'HRC BSP Approval Request'), ('NARC_COUNT_SHEET', 'Narc Count Sheet'), ('INCIDENT_CREATION', 'Incident Creation'), ('MONTHLY_PROGRESS_REPORT', 'Monthly Progress Report')], max_length=100)),
                ('frequency_type', models.CharField(choices=[('ONCE', 'Once'), ('PERIODIC', 'Periodic')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_forms', to='leads.lead')),
            ],
            options={
                'db_table': 'consent_forms',
            },
        ),
        migrations.CreateModel(
            name='ConsentFormEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('form_json', models.JSONField()),
                ('filled_at', models.DateTimeField()),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FILLED', 'Filled'), ('PENDING', 'Pending')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='document.consentform')),
            ],
            options={
                'db_table': 'consent_form_entries',
            },
        ),
        migrations.AddIndex(
            model_name='consentform',
            index=models.Index(fields=['form_code'], name='consent_for_form_co_3261da_idx'),
        ),
        migrations.AddIndex(
            model_name='consentform',
            index=models.Index(fields=['resident'], name='consent_for_residen_67fa23_idx'),
        ),
        migrations.AddIndex(
            model_name='consentformentry',
            index=models.Index(fields=['status'], name='consent_for_status_21a828_idx'),
        ),
        migrations.AddIndex(
            model_name='consentformentry',
            index=models.Index(fields=['form'], name='consent_for_form_id_a6d33d_idx'),
        ),
    ]
