# Generated by Django 6.0 on 2026-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_consentform_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentformentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
