# Generated by Django 6.0 on 2026-01-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_consentformentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentformentry',
            name='filled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
