# Generated by Django 6.0 on 2026-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_consentformentry_filled_at'),
        ('leads', '0005_leadgrouphomeassignment_unique_active_assignment_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='signer_type',
            field=models.CharField(blank=True, choices=[('GUARDIAN', 'Guardian'), ('AGENT', 'Agent')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='consentform',
            index=models.Index(fields=['signer_type'], name='consent_for_signer__ed7e34_idx'),
        ),
    ]
