# Generated by Django 6.0 on 2026-02-20 07:55

import uuid
from django.db import migrations, models


def populate_uuids(apps, schema_editor):
    ConsentFormEntry = apps.get_model('document', 'ConsentFormEntry')
    for entry in ConsentFormEntry.objects.all():
        entry.uuid = uuid.uuid4()
        entry.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_consentform_signer_type_and_more'),
    ]

    operations = [
        # Step 1: Add nullable, non-unique UUID field
        migrations.AddField(
            model_name='consentformentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Step 3: Make non-nullable and unique
        migrations.AlterField(
            model_name='consentformentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
