# Generated by Django 6.0 on 2026-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_consentformentry_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consentform',
            name='form_code',
            field=models.CharField(choices=[('MEDICAL_DEFERMENT_FORM', 'Medical Deferment Form'), ('HEALTH_HISTORY_FORM', 'Health History Form'), ('5_AND_30_DAY_NURSING_TRANSITION_EVALUATION_FORM', '5 And 30 Day Nursing Transition Evaluation Form'), ('RESIDENT_INVENTORY_LIST', 'Resident Inventory List'), ('FIRE_SAFETY_ASSESSMENT', 'Fire Safety Assessment'), ('HRST_MONTHLY_TRACKER', 'HRST Monthly Tracker'), ('CAFC_BSP_TEMPLATE', 'CAFC BSP (Behaviour Support Plan) Template'), ('MED_DISPOSAL_SHEET', 'Medication Disposal Sheet'), ('HRC_BSP_APPROVAL_REQUEST', 'HRC BSP Approval Request'), ('NARC_COUNT_SHEET', 'Narc Count Sheet'), ('INCIDENT_CREATION', 'Incident Creation'), ('MONTHLY_PROGRESS_REPORT', 'Monthly Progress Report'), ('NH_RESIDENCY_AGREEMENT', 'NH Residency Agreement'), ('CAFC_HOUSE_RULES', 'CAFC House Rules'), ('BLANK_ROI', 'Blank ROI'), ('SERVICE_AGREEMENT', 'Service Agreement')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consentformentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('SIGNED', 'Signed')], max_length=20),
        ),
    ]
