# Generated by Django 6.0 on 2026-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
