# Generated by Django 6.0 on 2026-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_provider_address_provider_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
