# Generated by Django 6.0 on 2026-05-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_options_provider_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name']},
        ),
    ]
