# Generated by Django 6.0 on 2026-05-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at']},
        ),
    ]
