# Generated by Django 6.0 on 2026-01-15 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='GroupHome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(blank=True, choices=[('Eastern Time', 'Eastern Time'), ('Central Time', 'Central Time'), ('Mountain Time', 'Mountain Time'), ('Pacific Time', 'Pacific Time'), ('Arizona Time', 'Arizona Time'), ('Alaska Time', 'Alaska Time')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('no_of_rooms', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_homes', to='accounts.address')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_homes', to='group_home.license')),
            ],
            options={
                'db_table': 'group_home',
            },
        ),
        migrations.CreateModel(
            name='GroupHomeRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('group_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='group_home.grouphome')),
            ],
            options={
                'db_table': 'group_home_rooms',
                'unique_together': {('group_home', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupHomeShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('group_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='group_home.grouphome')),
            ],
            options={
                'db_table': 'group_home_shifts',
                'unique_together': {('group_home', 'shift')},
            },
        ),
    ]
