# Generated by Django 6.0 on 2026-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphome',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
