# Generated by Django 6.0 on 2026-05-19 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_home', '0003_grouphomeroom_uuid_grouphomeshift_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHomeStaffAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_type', models.CharField(choices=[('DSP', 'DSP'), ('PROGRAM_MANAGER', 'Program Manager'), ('PROGRAM_COORDINATOR', 'Program Coordinator'), ('BCBA', 'BCBA'), ('NURSE', 'Nurse'), ('LEAD', 'Lead')], max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('group_home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='group_home.grouphome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_home_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_home_staff_assignments',
                'indexes': [models.Index(fields=['group_home', 'role_type', 'status'], name='group_home__group_h_bd07a7_idx'), models.Index(fields=['user', 'status'], name='group_home__user_id_1cd196_idx')],
                'unique_together': {('group_home', 'user', 'role_type')},
            },
        ),
    ]
