# Generated by Django 6.0 on 2026-01-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('group_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_home',
        ),
        migrations.AddField(
            model_name='user',
            name='group_homes',
            field=models.ManyToManyField(blank=True, related_name='users', to='group_home.grouphome'),
        ),
    ]
