# Generated by Django 6.0 on 2026-01-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_group_home_user_group_homes'),
        ('group_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_homes',
        ),
        migrations.AddField(
            model_name='user',
            name='group_home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='group_home.grouphome'),
        ),
    ]
