# Generated by Django 6.0 on 2026-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_group_homes_user_group_home'),
        ('group_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_home',
        ),
        migrations.AddField(
            model_name='user',
            name='group_homes',
            field=models.ManyToManyField(blank=True, related_name='users', to='group_home.grouphome'),
        ),
    ]
