# Generated by Django 6.0 on 2026-02-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_permission_uuid_permissionroles_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionroles',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All group homes'), ('ASSIGNED_HOME', 'Assigned group home(s) only')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionroles',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permission'),
        ),
        migrations.AlterField(
            model_name='permissionroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.role'),
        ),
    ]
