# Generated by Django 6.0 on 2026-02-24 07:32

from django.db import migrations


DEFAULT_ROLES = [
    {"name": "Admin",               "type": "ADMIN",               "description": "Full System Access"},
    {"name": "Program Director",    "type": "PROGRAM_DIRECTOR",    "description": "Full System Access"},
    {"name": "Program Manager",     "type": "PROGRAM_MANAGER",     "description": "Full System Access"},
    {"name": "BCBA",                "type": "BCBA",                "description": "Full System Access"},
    {"name": "Nurse",               "type": "NURSE",               "description": "Limited Access"},
    {"name": "Program Coordinator", "type": "PROGRAM_COORDINATOR", "description": "Scoped Access"},
    {"name": "DSP",                 "type": "DSP",                 "description": "Restricted Access"},
    {"name": "Lead",                "type": "LEAD",                "description": None},
    {"name": "Agent",               "type": "AGENT",               "description": None},
    {"name": "Guardian",            "type": "GUARDIAN",             "description": None},
    {"name": "Resident",            "type": "RESIDENT",            "description": None},
]


def seed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    for role_data in DEFAULT_ROLES:
        Role.objects.get_or_create(
            name=role_data["name"],
            defaults={
                "type": role_data["type"],
                "description": role_data["description"],
            },
        )


def unseed_roles(apps, schema_editor):
    """Reverse: delete only the roles we seeded (that haven't been modified)."""
    Role = apps.get_model("accounts", "Role")
    names = [r["name"] for r in DEFAULT_ROLES]
    Role.objects.filter(name__in=names, deleted_at__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_permissionroles_scope_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
