# Generated by Django 6.0 on 2026-02-24
# Seeds permissions, migrates old roles to new ones, and creates permission-role mappings.

from django.db import migrations


# ─── Role definitions (updated types) ───────────────────────────────────────
ROLES = [
    {"name": "Admin",               "type": "ADMIN"},
    {"name": "Program Director",    "type": "STAFF"},
    {"name": "Program Manager",     "type": "STAFF"},
    {"name": "BCBA",                "type": "STAFF"},
    {"name": "Nurse",               "type": "STAFF"},
    {"name": "Program Coordinator", "type": "STAFF"},
    {"name": "DSP",                 "type": "STAFF"},
    {"name": "Lead",                "type": "LEAD"},
    {"name": "Agent",               "type": "AGENT"},
    {"name": "Guardian",            "type": "GUARDIAN"},
    {"name": "Resident",            "type": "RESIDENT"},
]

# ─── Permission definitions: (name, module, sub_module, key) ────────────────
PERMISSIONS = [
    # Leads
    ("View Leads",               "leads",           None, "view"),
    ("Create Lead",              "leads",           None, "create"),
    ("Edit Lead",                "leads",           None, "edit"),
    ("Delete Lead",              "leads",           None, "delete"),
    ("Assign Lead",              "leads",           None, "assign"),
    # Onboarding
    ("Complete Onboarding",      "onboarding",      None, "complete"),
    ("Select Group Home / Room", "onboarding",      None, "select_group_home"),
    ("Select Check-in Date",     "onboarding",      None, "select_checkin_date"),
    ("Mark as Completed",        "onboarding",      None, "mark_completed"),
    ("Send Guardian Credentials","onboarding",      None, "send_guardian_credentials"),
    # Documents
    ("View Documents",           "documents",       None, "view"),
    ("Upload Document",          "documents",       None, "upload"),
    ("Download Document",        "documents",       None, "download"),
    ("Edit Document",            "documents",       None, "edit"),
    ("Delete Document",          "documents",       None, "delete"),
    ("Preview Document",         "documents",       None, "preview"),
    ("Print Document",           "documents",       None, "print"),
    ("Document Versioning",      "documents",       None, "versioning"),
    # Consent Forms
    ("View All Forms",           "consent_forms",   None, "view"),
    ("Fill New Form",            "consent_forms",   None, "create"),
    ("Edit Form",                "consent_forms",   None, "edit"),
    ("Save as Draft",            "consent_forms",   None, "save_draft"),
    ("Refill Existing Form",     "consent_forms",   None, "refill"),
    ("Print Form",               "consent_forms",   None, "print"),
    ("Share Form",               "consent_forms",   None, "share"),
    ("Delete Form",              "consent_forms",   None, "delete"),
    ("View Form History",        "consent_forms",   None, "view_history"),
    # ADLs
    ("View ADL Data",            "adls",            None, "view"),
    ("Record ADL Activities",    "adls",            None, "record"),
    ("Edit ADL Records",         "adls",            None, "edit"),
    ("Generate ADL Reports",     "adls",            None, "generate_report"),
    # Daily Tracking
    ("View Daily Logs",          "daily_tracking",  None, "view"),
    ("Create Daily Entry",       "daily_tracking",  None, "create"),
    ("Edit Daily Log",           "daily_tracking",  None, "edit"),
    # Monthly Summary
    ("View Monthly Summary",     "monthly_summary", None, "view"),
    ("Generate Report",          "monthly_summary", None, "generate_report"),
    ("Edit Monthly Summary",     "monthly_summary", None, "edit"),
    # Goals
    ("View Goals",               "goals",           None, "view"),
    ("Create Goal",              "goals",           None, "create"),
    ("Edit Goal",                "goals",           None, "edit"),
    ("Delete Goal",              "goals",           None, "delete"),
    ("Track Progress",           "goals",           None, "track_progress"),
    # Incidents
    ("View Incidents",           "incidents",       None, "view"),
    ("Filter / Search",          "incidents",       None, "search"),
    ("Add New Incident",         "incidents",       None, "create"),
    ("Edit Incident",            "incidents",       None, "edit"),
    ("Classify Incident",        "incidents",       None, "classify"),
    ("Set Alert",                "incidents",       None, "set_alert"),
    ("Assign Investigator",      "incidents",       None, "assign_investigator"),
    ("Document Corrective Actions", "incidents",    None, "corrective_actions"),
    ("Close Incident",           "incidents",       None, "close"),
    ("Print Report",             "incidents",       None, "print_report"),
    ("Comment",                  "incidents",       None, "comment"),
    # Appointments
    ("View Appointments",        "appointments",    None, "view"),
    ("Filter Appointments",      "appointments",    None, "filter"),
    ("Request New Appointment",  "appointments",    None, "create"),
    ("Edit Appointment",         "appointments",    None, "edit"),
    ("Mark as Completed",        "appointments",    None, "mark_completed"),
    ("Delete Appointment",       "appointments",    None, "delete"),
    # Group Homes
    ("View Group Homes",         "group_homes",     None, "view"),
    ("Add New Group Home",       "group_homes",     None, "create"),
    ("Edit Group Home",          "group_homes",     None, "edit"),
    ("View Profile",             "group_homes",     None, "view_profile"),
    ("Deactivate",               "group_homes",     None, "deactivate"),
    ("Delete",                   "group_homes",     None, "delete"),
    # Users
    ("View Users",               "users",           None, "view"),
    ("Add New User",             "users",           None, "create"),
    ("Edit User",                "users",           None, "edit"),
    ("Deactivate User",          "users",           None, "deactivate"),
    ("Role Assignment",          "users",           None, "role_assignment"),
    # Audit Logs
    ("View Audit History",       "audit_logs",      None, "view"),
    ("Filter by Group Home",     "audit_logs",      None, "filter_group_home"),
    ("Search by Staff",          "audit_logs",      None, "search_staff"),
    ("Track Data Changes",       "audit_logs",      None, "track_changes"),
    ("Monitor Security (IP)",    "audit_logs",      None, "monitor_security"),
    ("Add Log Entry",            "audit_logs",      None, "add_entry"),
    ("View House Logs",          "audit_logs",      None, "view_house_logs"),
]

# Helper: all permission (module, key) pairs
ALL_PERM_KEYS = [(p[1], p[3]) for p in PERMISSIONS]

# ─── Permission-Role mappings per role ──────────────────────────────────────
ROLE_PERMISSIONS = {
    # Full access roles — all 77 permissions, scope=ALL
    "Admin":             "ALL_PERMS",
    "Program Director":  "ALL_PERMS",
    "Program Manager":   "ALL_PERMS",
    "BCBA":              "ALL_PERMS",

    # Nurse — limited document access only
    "Nurse": [
        (("documents", "view"),       "ALL"),
        (("documents", "download"),   "ALL"),
        (("documents", "edit"),       "ALL"),
        (("documents", "preview"),    "ALL"),
        (("documents", "print"),      "ALL"),
        (("documents", "versioning"), "ALL"),
    ],

    # Program Coordinator — broad access scoped to assigned home
    "Program Coordinator": [
        (("onboarding", "complete"),               "ASSIGNED_HOME"),
        (("onboarding", "select_group_home"),      "ASSIGNED_HOME"),
        (("onboarding", "select_checkin_date"),     "ASSIGNED_HOME"),
        (("onboarding", "mark_completed"),          "ASSIGNED_HOME"),
        (("onboarding", "send_guardian_credentials"), "ASSIGNED_HOME"),
        (("documents", "view"),       "ASSIGNED_HOME"),
        (("documents", "upload"),     "ASSIGNED_HOME"),
        (("documents", "download"),   "ASSIGNED_HOME"),
        (("documents", "edit"),       "ASSIGNED_HOME"),
        (("documents", "delete"),     "ASSIGNED_HOME"),
        (("documents", "preview"),    "ASSIGNED_HOME"),
        (("documents", "print"),      "ASSIGNED_HOME"),
        (("documents", "versioning"), "ASSIGNED_HOME"),
        (("consent_forms", "view"),         "ASSIGNED_HOME"),
        (("consent_forms", "create"),       "ASSIGNED_HOME"),
        (("consent_forms", "edit"),         "ASSIGNED_HOME"),
        (("consent_forms", "save_draft"),   "ASSIGNED_HOME"),
        (("consent_forms", "refill"),       "ASSIGNED_HOME"),
        (("consent_forms", "print"),        "ASSIGNED_HOME"),
        (("consent_forms", "share"),        "ASSIGNED_HOME"),
        (("consent_forms", "delete"),       "ASSIGNED_HOME"),
        (("consent_forms", "view_history"), "ASSIGNED_HOME"),
        (("adls", "view"),            "ASSIGNED_HOME"),
        (("adls", "record"),          "ASSIGNED_HOME"),
        (("adls", "edit"),            "ASSIGNED_HOME"),
        (("adls", "generate_report"), "ASSIGNED_HOME"),
        (("daily_tracking", "view"),   "ASSIGNED_HOME"),
        (("daily_tracking", "create"), "ASSIGNED_HOME"),
        (("daily_tracking", "edit"),   "ASSIGNED_HOME"),
        (("monthly_summary", "view"),            "ASSIGNED_HOME"),
        (("monthly_summary", "generate_report"), "ASSIGNED_HOME"),
        (("monthly_summary", "edit"),            "ASSIGNED_HOME"),
        (("goals", "view"),           "ASSIGNED_HOME"),
        (("goals", "create"),         "ASSIGNED_HOME"),
        (("goals", "edit"),           "ASSIGNED_HOME"),
        (("goals", "delete"),         "ASSIGNED_HOME"),
        (("goals", "track_progress"), "ASSIGNED_HOME"),
        (("incidents", "view"),                "ASSIGNED_HOME"),
        (("incidents", "search"),              "ASSIGNED_HOME"),
        (("incidents", "create"),              "ASSIGNED_HOME"),
        (("incidents", "edit"),                "ASSIGNED_HOME"),
        (("incidents", "classify"),            "ASSIGNED_HOME"),
        (("incidents", "set_alert"),           "ASSIGNED_HOME"),
        (("incidents", "assign_investigator"), "ASSIGNED_HOME"),
        (("incidents", "corrective_actions"),  "ASSIGNED_HOME"),
        (("incidents", "close"),               "ASSIGNED_HOME"),
        (("incidents", "print_report"),        "ASSIGNED_HOME"),
        (("incidents", "comment"),             "ASSIGNED_HOME"),
        (("appointments", "view"),           "ASSIGNED_HOME"),
        (("appointments", "filter"),         "ASSIGNED_HOME"),
        (("appointments", "create"),         "ASSIGNED_HOME"),
        (("appointments", "edit"),           "ASSIGNED_HOME"),
        (("appointments", "mark_completed"), "ASSIGNED_HOME"),
        (("appointments", "delete"),         "ASSIGNED_HOME"),
        (("group_homes", "view"),         "ASSIGNED_HOME"),
        (("group_homes", "edit"),         "ASSIGNED_HOME"),
        (("group_homes", "view_profile"), "ASSIGNED_HOME"),
        (("audit_logs", "view_house_logs"), "ASSIGNED_HOME"),
    ],

    # DSP — restricted access scoped to assigned home
    "DSP": [
        (("adls", "view"),   "ASSIGNED_HOME"),
        (("adls", "record"), "ASSIGNED_HOME"),
        (("adls", "edit"),   "ASSIGNED_HOME"),
        (("daily_tracking", "view"),   "ASSIGNED_HOME"),
        (("daily_tracking", "create"), "ASSIGNED_HOME"),
        (("daily_tracking", "edit"),   "ASSIGNED_HOME"),
        (("goals", "view"),           "ASSIGNED_HOME"),
        (("goals", "track_progress"), "ASSIGNED_HOME"),
        (("incidents", "view"),         "ASSIGNED_HOME"),
        (("incidents", "search"),       "ASSIGNED_HOME"),
        (("incidents", "create"),       "ASSIGNED_HOME"),
        (("incidents", "print_report"), "ASSIGNED_HOME"),
        (("incidents", "comment"),      "ASSIGNED_HOME"),
        (("appointments", "view"),           "ASSIGNED_HOME"),
        (("appointments", "filter"),         "ASSIGNED_HOME"),
        (("appointments", "mark_completed"), "ASSIGNED_HOME"),
        (("group_homes", "view"),         "ASSIGNED_HOME"),
        (("group_homes", "view_profile"), "ASSIGNED_HOME"),
        (("audit_logs", "view_house_logs"), "ASSIGNED_HOME"),
    ],

    # These roles have no permissions
    "Lead":     [],
    "Agent":    [],
    "Guardian": [],
    "Resident": [],
}


def seed_permissions_and_mappings(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Permission = apps.get_model("accounts", "Permission")
    PermissionRoles = apps.get_model("accounts", "PermissionRoles")

    # 1. Ensure roles have correct types
    for role_data in ROLES:
        Role.objects.update_or_create(
            name=role_data["name"],
            defaults={"type": role_data["type"]},
        )

    # 2. Seed all permissions (matched on module + key)
    perm_cache = {}
    for name, module, sub_module, key in PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            module=module,
            key=key,
            defaults={
                "name": name,
                "sub_module": sub_module,
            },
        )
        perm_cache[(module, key)] = perm

    # 3. Seed permission-role mappings
    for role_name, perm_list in ROLE_PERMISSIONS.items():
        try:
            role = Role.objects.get(name=role_name)
        except Role.DoesNotExist:
            continue

        if perm_list == "ALL_PERMS":
            entries = [(mk, "ALL") for mk in ALL_PERM_KEYS]
        else:
            entries = perm_list

        for (module, key), scope in entries:
            perm = perm_cache.get((module, key))
            if not perm:
                continue
            PermissionRoles.objects.get_or_create(
                role=role,
                permission=perm,
                defaults={"scope": scope},
            )


def unseed_permissions_and_mappings(apps, schema_editor):
    """Reverse: remove seeded permission-role mappings and permissions."""
    Permission = apps.get_model("accounts", "Permission")
    PermissionRoles = apps.get_model("accounts", "PermissionRoles")

    module_key_pairs = [(p[1], p[3]) for p in PERMISSIONS]
    for module, key in module_key_pairs:
        perm = Permission.objects.filter(module=module, key=key).first()
        if perm:
            PermissionRoles.objects.filter(permission=perm).delete()

    for module, key in module_key_pairs:
        Permission.objects.filter(module=module, key=key).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_seed_default_roles"),
    ]

    operations = [
        migrations.RunPython(
            seed_permissions_and_mappings,
            unseed_permissions_and_mappings,
        ),
    ]
