# Generated by Django 6.0 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_permissions_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordotp',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordotp',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordotp',
            name='resend_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='passwordotp',
            index=models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_cd0603_idx'),
        ),
    ]
