# Generated by Django 6.0 on 2026-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_passwordotp_is_used_passwordotp_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionroles',
            name='display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
