# Generated by Django 6.0 on 2026-05-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_permissionroles_display'),
        ('group_home', '0003_grouphomeroom_uuid_grouphomeshift_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_homes',
            field=models.ManyToManyField(blank=True, related_name='multi_users', to='group_home.grouphome'),
        ),
    ]
