"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (if present)
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    "drf_spectacular",
    'corsheaders',  # CORS support
    'storages',  # Django storages for S3

    #new app 
    'accounts',
    "audit_logs",
    'leads',
    'group_home',
    'incidents',
    'appointments',
    'residents',
    'media',  # Media management app
    "document",
    "providers",  # Provider management
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.JWTAuthCookieMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.JWTCookieAuthentication',
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'login': '10/min',
        'forgot_password': '5/hour',
        'verify_otp': '10/hour',
        'resend_otp': '6/hour',
    },
}

# ============================================================================
# OTP Security Configuration
# ============================================================================
OTP_MAX_ATTEMPTS = 5                # Max wrong OTP tries before lockout
OTP_LOCKOUT_MINUTES = 15            # Lockout duration after max failures
OTP_EXPIRY_MINUTES = 5              # OTP validity window
OTP_RESEND_COOLDOWN_SECONDS = 60    # Minimum gap between resends
OTP_MAX_RESENDS = 3                 # Max resends within the rolling window
OTP_RESEND_WINDOW_MINUTES = 10      # Rolling window for resend rate-limit


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
         'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'OpenAPI definition',
    'VERSION': 'v0',
    'SERVERS': [
        {
            'url': os.getenv('BASE_URL'),
            'description': 'Generated server url',
        },
    ],
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = "accounts.User"


from datetime import timedelta
SIMPLE_JWT = {
    # Must stay comfortably above the frontend's 60s proactive-refresh buffer
    # (isAccessTokenExpired(60000) in cafc-frontend) - a lifetime <= 1 minute makes every
    # token "expired" at issue time and turns each API call into a refresh.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL")

CORS_ALLOW_ALL_ORIGINS = True

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://dev-cafcnh.aistrong.ai",
    "https://qa-cafcnh.aistrong.ai",
    "https://stage-cafcnh.aistrong.ai",
    "https://cafc-dev-bucket.s3.amazonaws.com",
]

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================================================
# AWS S3 Configuration for Media Storage
# ============================================================================

# AWS Credentials from environment variables
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')

# S3 Storage Backend Configuration
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# S3 Object Parameters
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # 24 hours
}

# S3 Security Settings
AWS_DEFAULT_ACL = None  # None = use bucket default (works with ACLs disabled)
AWS_S3_FILE_OVERWRITE = False  # Prevent file overwrite
AWS_QUERYSTRING_AUTH = True  # Enable signed URL generation
AWS_QUERYSTRING_EXPIRE = 3600  # Signed URL expiry: 1 hour (3600 seconds)

# Media URL Configuration
# Use CloudFront domain if available, otherwise use S3 bucket domain
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', '')
if AWS_S3_CUSTOM_DOMAIN:
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
else:
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/'

# File Upload Constraints
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB in bytes
ALLOWED_FILE_TYPES = [
    # Images
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/gif',
    # Documents
    'application/pdf',
    'application/msword',  # .doc
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  # .docx
    # Videos
    'video/mp4',
    # Office Documents
    'application/vnd.ms-excel',  # .xls
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',  # .xlsx
    'application/vnd.ms-powerpoint',  # .ppt
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',  # .pptx
]

# ============================================================================
# Email Configuration (Supports AWS SES and MailHog for testing)
# ============================================================================

# Email Backend - Use SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = os.getenv('AWS_SES_SMTP_HOST', '')
EMAIL_PORT = int(os.getenv('AWS_SES_SMTP_PORT', '587'))
EMAIL_USE_TLS = True  # Use TLS for port 587
EMAIL_HOST_USER = os.getenv('AWS_SES_SMTP_USERNAME', '')
EMAIL_HOST_PASSWORD = os.getenv('AWS_SES_SMTP_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('AWS_SES_DEFAULT_FROM_EMAIL', '')
# ============================================================================
# Logging Configuration (Django built-in logging)
# ============================================================================

# Create logs directory
LOGS_DIR = BASE_DIR / 'storage' / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Django uses Python's built-in logging module
# This configuration sets up file-based logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
