# Generated by Django 6.0 on 2026-01-15 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('ADL', 'ADL'), ('GOAL', 'Goal')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_care_plan_items', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_care_plan_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'care_plan_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanDailyLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('log_date', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('status', models.CharField(choices=[('WORKED', 'Worked'), ('DID_NOT_WORK', 'Did Not Work'), ('COULD_NOT_WORK', 'Could Not Work')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_care_plan_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_daily_logs', to=settings.AUTH_USER_MODEL)),
                ('care_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='residents.careplanitem')),
            ],
            options={
                'db_table': 'care_plan_daily_logs',
                'ordering': ['-log_date', '-created_at'],
                'unique_together': {('care_plan_item', 'resident', 'log_date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentCarePlanItemShift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('care_plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='residents.careplanitem')),
            ],
            options={
                'db_table': 'assignment_care_plan_item_shifts',
                'unique_together': {('care_plan_item', 'shift')},
            },
        ),
    ]
