# Generated by Django 6.0 on 2026-02-20 07:55

import uuid
from django.db import migrations, models


def populate_uuids(apps, schema_editor):
    Model = apps.get_model('residents', 'AssignmentCarePlanItemShift')
    for obj in Model.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_careplanreport'),
    ]

    operations = [
        # Step 1: Add nullable, non-unique UUID field
        migrations.AddField(
            model_name='assignmentcareplanitemshift',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Step 3: Make non-nullable and unique
        migrations.AlterField(
            model_name='assignmentcareplanitemshift',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
