# Generated by Django 6.0 on 2026-02-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_metadata'),
        ('residents', '0003_assignmentcareplanitemshift_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanreport',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plan_reports', to='media.media'),
        ),
    ]
