# Generated by Django 6.0 on 2026-02-23 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_metadata'),
        ('residents', '0004_careplanreport_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='careplanreport',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='careplanreport',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('resident', 'report_month', 'report_year'), name='unique_active_report_per_resident_month'),
        ),
    ]
