# Generated by Django 6.0 on 2026-05-15 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_add_updated_by_to_careplanitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentScheduledForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(help_text='Name of the form, e.g. "Schedule 30-Day ISA".', max_length=255)),
                ('scheduled_date', models.DateField(help_text='The date scheduled for the form.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(help_text='The resident (lead/user) this scheduled form belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_forms', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The staff user who created/last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resident_scheduled_forms',
                'ordering': ['-created_at'],
                'unique_together': {('resident', 'form_name')},
            },
        ),
    ]
