# Generated by Django 6.0 on 2026-05-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_residentscheduledform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residentscheduledform',
            unique_together={('user', 'form_name')},
        ),
        migrations.AlterField(
            model_name='residentscheduledform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='residentscheduledform',
            name='user',
            field=models.ForeignKey(help_text='The resident (User) this scheduled form belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='residentscheduledform',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='residentscheduledform',
            name='scheduled_date',
        ),
    ]
