# Generated by Django 6.0 on 2026-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_alter_residentscheduledform_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentscheduledform',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The date scheduled for the form.', null=True),
        ),
    ]
