# Generated by Django 6.0 on 2026-02-10 09:27

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='metadata',
            field=models.JSONField(blank=True, default=media.models.default_media_metadata, help_text='Extra metadata like signing info'),
        ),
    ]
