# Generated by Django 6.0 on 2026-01-15 12:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('incident_datetime', models.DateTimeField(blank=True, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_incident_notes', models.TextField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('response_action', models.TextField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentLegalFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('legal_type', models.CharField(max_length=255)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_flags', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMedicalFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medical_type', models.CharField(max_length=255)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_flags', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentSocialFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social_type', models.CharField(max_length=255)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_flags', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentVictimFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('victim_type', models.CharField(max_length=255)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_flags', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_victim_flags',
            },
        ),
    ]
