# Generated by Django 6.0 on 2026-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
