# Generated by Django 6.0 on 2026-02-05 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SERVICE_COORDINATOR', 'Service Coordinator'), ('PROGRAM_MANAGER', 'Program Manager'), ('GUARDIAN', 'Guardian'), ('NURSING', 'Nursing'), ('ADDITIONAL_SERVICE_PROVIDER', 'Additional Service Provider')], max_length=50)),
                ('notify', models.BooleanField(default=False)),
                ('notify_date', models.DateField(blank=True, null=True)),
                ('notify_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notifications', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_notifications',
            },
        ),
    ]
