# Generated by Django 6.0 on 2026-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incidentnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentnotification',
            name='type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('SERVICE_COORDINATOR', 'Service Coordinator'), ('PROGRAM_MANAGER', 'Program Manager'), ('GUARDIAN', 'Guardian'), ('NURSING', 'Nursing'), ('ADDITIONAL_SERVICE_PROVIDER', 'Additional Service Provider')], max_length=50),
        ),
    ]
