# Generated by Django 6.0 on 2026-02-11 12:37

from django.db import migrations, models


def convert_status(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")

    for incident in Incident.objects.all():
        if incident.status is True:
            incident.status = "OPEN"
        else:
            incident.status = "CLOSED"
        incident.save()

class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incidentnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ACKNOWLEDGED', 'Acknowledged')], default='OPEN', max_length=20),
        ),
        migrations.RunPython(convert_status),
    ]
