# Generated by Django 6.0 on 2026-02-20 07:55

import uuid
from django.db import migrations, models


MODEL_NAMES = (
    'IncidentLegalFlag',
    'IncidentMedicalFlag',
    'IncidentNotification',
    'IncidentSocialFlag',
    'IncidentVictimFlag',
)


def populate_uuids(apps, schema_editor):
    for model_name in MODEL_NAMES:
        Model = apps.get_model('incidents', model_name)
        for obj in Model.objects.all():
            obj.uuid = uuid.uuid4()
            obj.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incident_status'),
    ]

    operations = [
        # Step 1: Add nullable, non-unique UUID fields
        migrations.AddField(
            model_name='incidentlegalflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='incidentmedicalflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='incidentnotification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='incidentsocialflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='incidentvictimflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Step 3: Make non-nullable and unique
        migrations.AlterField(
            model_name='incidentlegalflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentmedicalflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentnotification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentsocialflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='incidentvictimflag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
