# Generated by Django 6.0 on 2026-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentlegalflag_uuid_incidentmedicalflag_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
