# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_add_incident_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='medical_other_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='social_other_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
