# Generated by Django - move medical_other_details to IncidentMedicalFlag,
# social_other_details to IncidentSocialFlag; copy data from Incident then remove from Incident.

from django.db import migrations, models


def copy_other_details_to_flags(apps, schema_editor):
    """Copy medical_other_details from Incident to its 'other' medical flag; same for social."""
    Incident = apps.get_model("incidents", "Incident")
    for incident in Incident.objects.all():
        medical_details = getattr(incident, "medical_other_details", None) or ""
        social_details = getattr(incident, "social_other_details", None) or ""
        if medical_details:
            incident.medical_flags.filter(medical_type="other").update(
                medical_other_details=medical_details
            )
        if social_details:
            incident.social_flags.filter(social_type="other").update(
                social_other_details=social_details
            )


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0009_add_medical_social_other_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentmedicalflag",
            name="medical_other_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="incidentsocialflag",
            name="social_other_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(copy_other_details_to_flags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="incident",
            name="medical_other_details",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="social_other_details",
        ),
    ]
