# Generated by Django 6.0 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_remove_incident_comment_incidentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentnotification',
            name='by_whom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentnotification',
            name='method_of_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
