# Generated by Django 6.0 on 2026-05-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_home', '0005_backfill_staff_assignments'),
        ('incidents', '0012_incidentnotification_by_whom_and_more'),
        ('media', '0002_media_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_program_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='group_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='group_home.grouphome'),
        ),
        migrations.AddField(
            model_name='incident',
            name='pm_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_for_incidents', to='media.media'),
        ),
        migrations.AddField(
            model_name='incident',
            name='program_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_for_incidents', to='media.media'),
        ),
        migrations.AddField(
            model_name='incident',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('PM_REVIEW_PENDING', 'Program Manager Review Pending'), ('COMPLETED', 'Completed'), ('ACKNOWLEDGED', 'Acknowledged')], default='DRAFT', max_length=20),
        ),
    ]
