# Generated by Django 6.0 on 2026-05-19 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_map_legacy_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEdit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_changes', models.JSONField(default=dict)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_edits', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_edits',
                'ordering': ['edited_at'],
            },
        ),
    ]
