# Generated by Django 6.0 on 2026-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_incidentedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentnotification',
            name='type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('SERVICE_COORDINATOR', 'Service Coordinator'), ('PROGRAM_MANAGER', 'Program Manager'), ('GUARDIAN', 'Guardian'), ('AGENT', 'Agent'), ('NURSING', 'Nursing'), ('ADDITIONAL_SERVICE_PROVIDER', 'Additional Service Provider')], max_length=50),
        ),
    ]
