# Generated by Django 6.0 on 2026-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_notification_agent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='pm_behavior_plan_followed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('N_A', 'N/A')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pm_program_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pm_review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pm_service_transition',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='pm_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
